### ISSUE TITLE
"Microsoft Coporation" typo in project files

### ISSUE THREAD

**Issue by florelis** [microsoft/CosmosDB-Solution-Accelerator-CosmosDB-Helper#6]
Several project files have a typo in the company name, writing Coporation instead of Corporation. For example:
https://github.com/microsoft/CosmosDB-Solution-Accelerator-CosmosDB-Helper/blob/78166f9a267d9f5a9722d7ae8f122f4833cb7c85/src/Libraries/Microsoft.Solutions.CosmosDB/Microsoft.Solutions.CosmosDB.csproj#L9

**Comment by Dongbumlee** [comment]
> Several project files have a typo in the company name, writing Coporation instead of Corporation. For example:
> 
> https://github.com/microsoft/CosmosDB-Solution-Accelerator-CosmosDB-Helper/blob/78166f9a267d9f5a9722d7ae8f122f4833cb7c85/src/Libraries/Microsoft.Solutions.CosmosDB/Microsoft.Solutions.CosmosDB.csproj#L9

Thanks for your feedback. let me fix the company name in each project files. :)
